language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: islomar-github
    token:
      secure: $SONARCLOUD_TOKEN

- stage: unit-test
  script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  after_success:
    - mvn clean test jacoco:report coveralls:report

- stage: end2end-test
  script:
    - mvn clean test -Pend2end

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'